---
include:
  - "lib/**/*.rb"
exclude:
  - "spec/**/*.rb"
  - ".bundle/**/*"
  - "Gemfile"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  # - typecheck:strict
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
